POST http://localhost:5208/api/Auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "test13@example.com",
  "username": "blablabla4",
  "phoneNumber": "1234567890",
  "firstName": "Test",
  "lastName": "User",
  "password": "changemE@123",
  "globalRole": "orguser",
  "nationalId": "12345678",
  "dateOfBirth": "2005-05-12",
  "organizationRole":"Owner"
  }

###

POST http://localhost:5208/api/Auth/login
Content-Type: application/json
Accept: application/json

{
  "userName": "superadmin",
  "password": "ChangeMe123!"
  }



