POST http://localhost:5208/api/Auth/register
Content-Type: application/json
Accept: application/json

{
  "email": "rider4@example.com",
  "username": "rider4",
  "phoneNumber": "1234567822",
  "firstName": "Test",
  "lastName": "User",
  "password": "changemE@123",
  "globalRole": "orguser",
  "nationalId": "123456333",
  "dateOfBirth": "2005-05-12",
  "organizationRole":"rider",
  "organizationId":"AD8EA38C-36C2-48E9-B6D8-558EC4D9EE8B"
  }

###

POST http://localhost:5208/api/Auth/login
Content-Type: application/json
Accept: application/json

{
  "userName": "superadmin",
  "password": "ChangeMe123!"
    # "password": "ChangeMe123!" 

  # "password": "changemE@123"

}

###


PUT http://localhost:5208/api/Auth/approve/superadmin/8B7D87AF-8EFE-4B2D-9B40-A95B80A6DB62
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQ4N2QxZGI2LTkzMjEtNDMyMy05YWYxLTYxNTdmODVkMjc0NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1cGVyYWRtaW5AZGVsaXZlcmEuY29tIiwiT3JnSWQiOiIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIiLCJSb2xlIjoiU3VwZXJBZG1pbiIsImV4cCI6MTc1ODkzNTM2OCwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.NiOzlmNW57OtOXKUjWGiuSGqrlv2-bd7vrcNWaSnJ10


###
POST http://localhost:5208/api/Auth/approve/orgowner/0E7696FA-813A-4E83-B1E8-9D05C2A1EB2C
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlNzY5NmZhLTgxM2EtNGU4My1iMWU4LTlkMDVjMmExZWIyYyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJibGFibGFibGEyIiwiUm9sZSI6Ik9yZ1VzZXIiLCJleHAiOjE3NTY1MjkyMTAsImlzcyI6IkRlbGl2ZXJhIiwiYXVkIjoiRGVsaXZlcmFVc2VycyJ9.oGFne1GGND70_iOFEPaVJbmXI48xQwlytaRi_whsuwA


###
POST http://localhost:5208/api/Auth/createorder/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI5Nzk0YzhlLWRhZjEtNGU4Ni05YTE0LThiZWY2NDkxNzY0OCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9yZ2FkbWluNEBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJSb2xlIjoiT3JnVXNlciIsImV4cCI6MTc1ODQ3NTU2MywiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.8S1bA675E6Pbnp3Nz_L4xlvZtO8ObTpO8rpUhlLSGGg

{
  "organizationId": "AD8EA38C-36C2-48E9-B6D8-558EC4D9EE8B",
  "orderDetails":"2 chips 1 peps",
  "pickUpLocation": {
    "address":"test address",
    "latitude":"22.22",
    "longtitude":"55.55"

  },
  "dropOffLocation":  {
    "address":"test address",
    "latitude":"22.22",
    "longtitude":"55.55"

  }
}

###
POST http://localhost:5208/api/Auth/zones/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjBlNzY5NmZhLTgxM2EtNGU4My1iMWU4LTlkMDVjMmExZWIyYyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3QxMUBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiT3duZXIiLCJleHAiOjE3NTcyMTExODYsImlzcyI6IkRlbGl2ZXJhIiwiYXVkIjoiRGVsaXZlcmFVc2VycyJ9.mJ15t4VzKD9TKNUvpkXQT0Y8dPzQwHjhC76wA2iDJZQ

{
  "name": "MyTestZone",
  "wktPolygon": "POLYGON((55.2462959 25.2407366,55.2692127 25.2293236,55.2353096 25.1892531,55.2141094 25.2048635,55.2458668 25.2412024,55.2462959 25.2407366))"
}


###
GET http://localhost:5208/api/Auth/getzone/19ff2521-f646-4a68-a3b2-ce31bd7ba810
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI5Nzk0YzhlLWRhZjEtNGU4Ni05YTE0LThiZWY2NDkxNzY0OCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9yZ2FkbWluNEBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJleHAiOjE3NTcxMDU5NjMsImlzcyI6IkRlbGl2ZXJhIiwiYXVkIjoiRGVsaXZlcmFVc2VycyJ9.NNVrFAHzpd1z3q7R3iqOB7rCBGozYCm_6CESLyJIvF4



###
PUT http://localhost:5208/api/Auth/assignRider/?orderId=43520544-D8BF-487E-8260-565CEACDB5CE
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI5Nzk0YzhlLWRhZjEtNGU4Ni05YTE0LThiZWY2NDkxNzY0OCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9yZ2FkbWluNEBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJSb2xlIjoiT3JnVXNlciIsImV4cCI6MTc1ODQ2OTY3MiwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.gIQby_bR_fMGbiRpG3PKhiLkyKSaHWY5ejv9jTm4a7c

###
PUT http://localhost:5208/api/Auth/update/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZmZTMzNDI0LTE5OTYtNGVmMC1iMGQxLTZkOTJiMzM3ZWY4YiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InJpZGVyMUBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUmlkZXIiLCJleHAiOjE3NTcyMTE4NzMsImlzcyI6IkRlbGl2ZXJhIiwiYXVkIjoiRGVsaXZlcmFVc2VycyJ9.pUatlnQlPwvnPg11EPKqWFHPXaGVSuszaKWoDAbI6K4

{
    "latitude":25.2067526005449,
    "longitude":55.2432909777042
    
}
###
PUT http://localhost:5208/api/Auth/endridersession/78157418-169E-40FC-9BE5-0A87E30719D8/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjJhMTViNDNjLWE2OWEtNDNhOS04N2JmLTFkMDFlODY2MmNlYSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9yZ3N1cHBvcnQxQGV4YW1wbGUuY29tIiwiT3JnSWQiOiJhZDhlYTM4Yy0zNmMyLTQ4ZTktYjZkOC01NThlYzRkOWVlOGIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiJTdXBwb3J0IiwiUm9sZSI6Ik9yZ1VzZXIiLCJleHAiOjE3NTg5MjA4MzUsImlzcyI6IkRlbGl2ZXJhIiwiYXVkIjoiRGVsaXZlcmFVc2VycyJ9.QrdxYTircYTS3BKF0MR-ete5Hc16p8poS2FGW90FH1s



###
PATCH http://localhost:5208/api/Auth/superadmin/approveOrg/BF8E4137-3806-49A3-AF14-757F308440DB
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQ4N2QxZGI2LTkzMjEtNDMyMy05YWYxLTYxNTdmODVkMjc0NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1cGVyYWRtaW5AZGVsaXZlcmEuY29tIiwiT3JnSWQiOiIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIiLCJSb2xlIjoiU3VwZXJBZG1pbiIsImV4cCI6MTc1ODkzNTM2OCwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.NiOzlmNW57OtOXKUjWGiuSGqrlv2-bd7vrcNWaSnJ10



###
GET http://localhost:5208/api/Auth/organizations/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQ4N2QxZGI2LTkzMjEtNDMyMy05YWYxLTYxNTdmODVkMjc0NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1cGVyYWRtaW5AZGVsaXZlcmEuY29tIiwiT3JnSWQiOiIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIiLCJSb2xlIjoiU3VwZXJBZG1pbiIsImV4cCI6MTc1NzIyOTM1MiwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.XqC9n2UWROuIMQ_hLINSCYyQ0nZbSkEBvCGMAqAz6t4


###
PATCH http://localhost:5208/api/Auth/updateorderstatus/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjI5Nzk0YzhlLWRhZjEtNGU4Ni05YTE0LThiZWY2NDkxNzY0OCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6Im9yZ2FkbWluNEBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiQWRtaW4iLCJSb2xlIjoiT3JnVXNlciIsImV4cCI6MTc1ODkxODQ0MywiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.uXdOBO-l2J-rsHT1twjO1kmi3aAraC9C3vjjRroJU98

{
  "status":"Canceled",
  "orderId":"43520544-D8BF-487E-8260-565CEACDB5CE"
}

###
GET http://localhost:5208/api/Auth/orders/68F84BED-BC41-47B1-87E2-D8D7C256E7CF
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZmZTMzNDI0LTE5OTYtNGVmMC1iMGQxLTZkOTJiMzM3ZWY4YiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InJpZGVyMUBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUmlkZXIiLCJSb2xlIjoiT3JnVXNlciIsImV4cCI6MTc1NzMyNjQ5NSwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.cuV07EV2zwjZHbB7jmTCPDWNdwDaUI6i6atcmPR0XYg

###
GET http://localhost:5208/api/Auth/orders/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjhiN2Q4N2FmLThlZmUtNGIyZC05YjQwLWE5NWI4MGE2ZGI2MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InRlc3QxMkBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiZDc1YjE1ZmEtNmY5YS00Mjk3LWEzNmUtODBmZTc0YjMxZmFjIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiT3duZXIiLCJSb2xlIjoiT3JnVXNlciIsImV4cCI6MTc1NzMyODMzOSwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.13lKm81ifm4YkgzxZXl-XoTkmcSfgRMLw5CSZ8hC48E

###
GET http://localhost:5208/api/Auth/orders/superadmin/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImQ4N2QxZGI2LTkzMjEtNDMyMy05YWYxLTYxNTdmODVkMjc0NCIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InN1cGVyYWRtaW5AZGVsaXZlcmEuY29tIiwiT3JnSWQiOiIiLCJodHRwOi8vc2NoZW1hcy5taWNyb3NvZnQuY29tL3dzLzIwMDgvMDYvaWRlbnRpdHkvY2xhaW1zL3JvbGUiOiIiLCJSb2xlIjoiU3VwZXJBZG1pbiIsImV4cCI6MTc1NzMyODg0NiwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.B8QEgIqXocHUDv9QkBUw22U_lpT5ZE_4PUdO7WhM18Y

###
GET http://localhost:5208/api/Auth/orders/own/
Content-Type: application/json
Accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6IjZmZTMzNDI0LTE5OTYtNGVmMC1iMGQxLTZkOTJiMzM3ZWY4YiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL2VtYWlsYWRkcmVzcyI6InJpZGVyMUBleGFtcGxlLmNvbSIsIk9yZ0lkIjoiYWQ4ZWEzOGMtMzZjMi00OGU5LWI2ZDgtNTU4ZWM0ZDllZThiIiwiaHR0cDovL3NjaGVtYXMubWljcm9zb2Z0LmNvbS93cy8yMDA4LzA2L2lkZW50aXR5L2NsYWltcy9yb2xlIjoiUmlkZXIiLCJSb2xlIjoiT3JnVXNlciIsImV4cCI6MTc1NzY5MzIzNiwiaXNzIjoiRGVsaXZlcmEiLCJhdWQiOiJEZWxpdmVyYVVzZXJzIn0.1BRHgZqlKVhIMd2uZ_N_iNVGecTq8DgAts2CJS8SzlQ

